package com.rebaze.mystique;

import okio.*;

import java.io.*;
import java.util.ArrayList;
import java.util.List;

import static com.rebaze.mystique.MutationBuilder.mutation;
import static okio.Okio.buffer;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tonit' at '10/15/16 3:54 PM' with Gradle 3.1
 *
 * @author tonit, @date 10/15/16 3:54 PM
 */
public class Mystique
{
    private final File target;

    public Mystique(  File target )
    {
        System.out.println("    __  ___              __   _                   \n"
            + "   /  |/  /__  __ _____ / /_ (_)____ _ __  __ ___ \n"
            + "  / /|_/ // / / // ___// __// // __ `// / / // _ \\\n"
            + " / /  / // /_/ /(__  )/ /_ / // /_/ // /_/ //  __/\n"
            + "/_/  /_/ \\__, //____/ \\__//_/ \\__, / \\__,_/ \\___/ \n"
            + "        /____/                  /_/               ");

        this.target = target;
    }

    public void exec(Universe input, MutationContext ctx, Materializer mat) throws IOException
    {
        ctx.applyTo( input );
        mat.materialize( input );
    }
}
